
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Signin</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
<?php
if(!isset($_GET['utma'])){
    echo '

      <form class="form-signin" role="form" >
        <h2 class="form-signin-heading">Авторизируйтесь</h2>
       
    
        
        <input class="form-control" placeholder="UTMA" type="text" name="utma" value="" required autofocus> 
   
    
        
        <input class="form-control" type="text" placeholder="UTMB" name="utmb" value="" required> 
    
    
        
        <input class="form-control" type="text" placeholder="UTMC" name="utmc" value="" required> 
    
    
        
        <input class="form-control" type="text" placeholder="UTMZ" name="utmz" value="" required>  
    
   
       
        <input class="form-control" type="text" placeholder="XSRF" name="xsrf" value="" required> 
    
    
        
        <input class="form-control" type="text" placeholder="lang" name="lang" value="ru_RU"> 
    
        
        <input class="form-control" type="text" placeholder="Token" name="token" value="" required> 
        
<input class="form-control" type="text" placeholder="USER-AGENT" name="user_agent" value="" required>
    
       

        <button class="btn btn-lg btn-primary btn-block" type="submit">Готово</button>
      </form>

    ';
}else{
    $utma =  $_GET['utma'];
    $utmb =  $_GET['utmb'];
    $utmc =  $_GET['utmc'];
    $cook = md5('l1al'.$utmc.$utma.$utmb);
    $handle = fopen("users/$cook.txt", "w+");
    
    $text = '# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.gameminer.ru	FALSE	/	FALSE	1724595000	lang	ru_RU
.gameminer.ru	FALSE	/	FALSE	1724595000	_xsrf	'.$_GET['xsrf'].'
.gameminer.ru	FALSE	/	FALSE	1724595000	_utma	'.$_GET['utma'].'
.gameminer.ru	FALSE	/	FALSE	1724595000	_utmb	'.$_GET['utmb'].'
.gameminer.ru	FALSE	/	FALSE	1724595000	_utmc	'.$_GET['utmc'].'
.gameminer.ru	FALSE	/	FALSE	1724595000	_utmz	'.$_GET['utmz'].'
.gameminer.ru	FALSE	/	FALSE	1724595000	token	'.$_GET['token'].'
';
    fwrite($handle, $text);
    if(!empty($_GET['user_agent'])){
        $user_agent = $_GET['user_agent'];
    }else{
         $user_agent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36';
   
    }
    $howIs = testAuth($cook,$user_agent);
    //print_r($howIs);
    if($howIs){
        session_start();
        $_SESSION['xsrf'] = $_GET['xsrf'];
        $_SESSION['cook'] = $cook;
        $_SESSION['agent'] = $_GET['user_agent'];
       echo 'Успешная авторизация,сохраните ссылку на эту страницу. <a href="main.php">Продолжить</a> '; 
    }else{
        echo 'Ошибка,<a href="index.php"> попробуйте ещё раз</a>';
    }
    //print_r($handle);
}

function testAuth($cook,$user_agent){
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, 'http://gameminer.ru');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_USERAGENT, $user_agent);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($curl, CURLOPT_COOKIEFILE, $_SERVER['DOCUMENT_ROOT']."/maining/users/$cook.txt");
    curl_setopt($curl, CURLOPT_COOKIEJAR, $_SERVER['DOCUMENT_ROOT']."/maining/users/$cook.txt");
    $html = curl_exec($curl);
    //print_r($html);
    curl_close($curl);
    
    
    //echo $html;
    if(preg_match('/Выйти/i', $html)){
        return 1;
    }else{
        return 0;
    }

}
?>    
        </div>
    <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

    
